Repository tModLoader/tModLoader, pull requests merged in 2022-05, with the labels that each got.

#2333 Add a shortcut from save dir to logs dir
  patches/tModLoader/Terraria/ModLoader/Core/FolderShortcutSupport.cs
  patches/tModLoader/Terraria/ModLoader/ModLoader.cs
Labels: Safe to Test

#2314 [1.4] [Feature] Clone method for Terraria.Recipe
  ExampleMod/Content/ExampleRecipes.cs
  patches/tModLoader/Terraria/ModLoader/Mod.cs
  patches/tModLoader/Terraria/Recipe.Extensions.cs
  patches/tModLoader/Terraria/Recipe.TML.cs
Labels: Improvement

#2308 [1.4] Fixed The Bee's Knees double-firing
  patches/tModLoader/Terraria/Item.cs.patch
Labels: ItemReworkPR

#2284 Accept dots in hjson
  patches/tModLoader/Terraria/ModLoader/LocalizationLoader.cs
Labels: Safe to Test

#2277 Re-implemented internal names for AddEquipTexture() and ported the equip methods from Mod to EquipLoader
  ExampleMod/Common/Players/ExampleCostumePlayer.cs
  ExampleMod/Content/Items/Armor/ExampleCostume.cs
  ExampleMod/Content/Items/Armor/ExampleCostumeAlt_Body.png
  ExampleMod/Content/Items/Armor/ExampleCostumeAlt_Head.png
  ExampleMod/Content/Items/Armor/ExampleCostumeAlt_Legs.png
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Jofairden_Head.cs
  patches/tModLoader/Terraria/ModLoader/Default/Patreon/Orian.cs
  patches/tModLoader/Terraria/ModLoader/EquipLoader.cs
  patches/tModLoader/Terraria/ModLoader/EquipTexture.cs
  patches/tModLoader/Terraria/ModLoader/Mod.cs
  patches/tModLoader/Terraria/ModLoader/ModItem.cs
Labels: Safe to Test

#2357 Fixes #2194 fully. Part 2 of High DPI to fix windows detection
  patches/tModLoader/Terraria/Main.cs.patch
  patches/tModLoader/Terraria/Program.TML.cs
Labels: Safe to Test

#2356 The Grand French Localization Update
  patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/fr-FR/tModLoader.json
Labels: Safe to Test

#2398 Add Mod/GlobalType NewInstance, IsCloneable, Clone and CloneNewInstances
  ExampleMod/Content/Items/Consumables/ExampleCanStackItem.cs
  ExampleMod/Content/Items/ExampleInstancedItem.cs
  patches/tModLoader/Terraria/Item.TML.cs
  patches/tModLoader/Terraria/ModLoader/Core/HookList.cs
  patches/tModLoader/Terraria/ModLoader/Core/LoaderUtils.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/JofairdenArmorEffectPlayer.cs
  patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
  patches/tModLoader/Terraria/ModLoader/Default/StartBag.cs
  patches/tModLoader/Terraria/ModLoader/Default/UnloadedGlobalItem.cs
  patches/tModLoader/Terraria/ModLoader/Default/UnloadedItem.cs
  patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
  patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
  patches/tModLoader/Terraria/ModLoader/GlobalProjectile.cs
  patches/tModLoader/Terraria/ModLoader/GlobalType.cs
  patches/tModLoader/Terraria/ModLoader/Instanced.cs
  patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/ModLoader/ModItem.cs
  patches/tModLoader/Terraria/ModLoader/ModLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModMount.cs
  patches/tModLoader/Terraria/ModLoader/ModNPC.cs
  patches/tModLoader/Terraria/ModLoader/ModPlayer.cs
  patches/tModLoader/Terraria/ModLoader/ModProjectile.cs
  patches/tModLoader/Terraria/ModLoader/ModSystem.cs
  patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
  patches/tModLoader/Terraria/ModLoader/ModType.cs
  patches/tModLoader/Terraria/ModLoader/MountLoader.cs
  patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
  patches/tModLoader/Terraria/ModLoader/PlayerLoader.cs
  patches/tModLoader/Terraria/ModLoader/ProjectileLoader.cs
  patches/tModLoader/Terraria/ModLoader/SystemLoader.HookLists.cs
Labels: Safe to Test
