Repository tModLoader/tModLoader, pull requests merged in 2022-09, with the labels that each got.

#2632 Custom Game Tips
  ExampleMod/Common/Systems/ExampleGameTipsSystem.cs
  ExampleMod/Localization/en-US.hjson
  patches/tModLoader/Terraria/GameContent/UI/GameTipsDisplay.TML.cs
  patches/tModLoader/Terraria/GameContent/UI/GameTipsDisplay.cs.patch
  patches/tModLoader/Terraria/ModLoader/GameTipData.cs
  patches/tModLoader/Terraria/ModLoader/GameTipID.cs
  patches/tModLoader/Terraria/ModLoader/LocalizationLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/ModLoader/ModSystem.cs
  patches/tModLoader/Terraria/ModLoader/SystemLoader.HookLists.cs
  patches/tModLoader/Terraria/ModLoader/SystemLoader.cs
Labels: Feature - Hook, Benefit - Medium, Complexity - Low

#2944 [1.4] Fully unload Jofairden armor assets
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenBodyGlow.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenBodyShader.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenHeadGlow.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenHeadShader.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenLegsGlow.cs
  patches/tModLoader/Terraria/ModLoader/Default/Developer/Jofairden/Layers/JofairdenLegsShader.cs
  patches/tModLoader/Terraria/ModLoader/Default/Patreon/Guildpack.cs
Labels: Bug, Benefit - Low, Complexity - Low

#2937 [1.4] Allow usage of non public constructors
  patches/tModLoader/Terraria/ModLoader/Config/ConfigManager.cs
  patches/tModLoader/Terraria/ModLoader/Config/UI/ObjectElement.cs
  patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs
  patches/tModLoader/Terraria/ModLoader/GlobalType.cs
  patches/tModLoader/Terraria/ModLoader/Loader.cs
  patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs
  patches/tModLoader/Terraria/ModLoader/Mod.cs
  patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
  patches/tModLoader/Terraria/ModLoader/ModType.cs
Labels: Benefit - Low, Complexity - Low

#2939 [1.4] Fix modded generation passes not being removed
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/WorldGen.TML.cs
Labels: Benefit - Low, Complexity - Low

#2954 Fixed poor implementation of Load() in ModTileEntity.
  patches/tModLoader/Terraria/ModLoader/ModTileEntity.cs
Labels: Benefit - Medium, Complexity - Low, Feature - Modder Experience

#2938 [1.4] `Mod/GlobalWall.WallFrame` hook
  ExampleMod/Common/GlobalWalls/ExampleGlobalWall.cs
  ExampleMod/Content/Items/Placeable/ExampleWallAdvanced.cs
  ExampleMod/Content/Items/Placeable/ExampleWallAdvanced.png
  ExampleMod/Content/Walls/ExampleWallAdvanced.cs
  ExampleMod/Content/Walls/ExampleWallAdvanced.png
  ExampleMod/Old/Walls/ExampleWall.cs
  ExampleMod/Old/Walls/ExampleWall.png
  patches/tModLoader/Terraria/Framing.cs.patch
  patches/tModLoader/Terraria/ID/TileID.TML.cs
  patches/tModLoader/Terraria/ModLoader/GlobalWall.cs
  patches/tModLoader/Terraria/ModLoader/ModBlockType.cs
  patches/tModLoader/Terraria/ModLoader/ModWall.cs
  patches/tModLoader/Terraria/ModLoader/WallLoader.cs
Labels: Feature - Hook, Benefit - Low, Complexity - Low, Resources - ExampleMod, Resources - Documentation, Resources - Wiki

#2869 OnStack Hook
  ExampleMod/Common/GlobalItems/ItemWithGrowingDamage.cs
  ExampleMod/Common/GlobalItems/WeaponWithGrowingDamage.cs
  ExampleMod/Common/GlobalProjectiles/ProjectileWithGrowingDamage.cs
  ExampleMod/Content/Items/Consumables/ExampleMultiUseItem.cs
  ExampleMod/Content/Items/Consumables/ExampleMultiUseItem.png
  ExampleMod/Content/Items/ExampleStackableDurabilityItem.cs
  ExampleMod/Content/Items/ExampleStackableDurabilityItem.png
  ExampleMod/Localization/en-US.hjson
  patches/tModLoader/Terraria/Chest.cs.patch
  patches/tModLoader/Terraria/GameContent/Tile_Entities/TEFoodPlatter.cs.patch
  patches/tModLoader/Terraria/GameContent/Tile_Entities/TEItemFrame.cs.patch
  patches/tModLoader/Terraria/GameContent/Tile_Entities/TEWeaponsRack.cs.patch
  patches/tModLoader/Terraria/GameInput/PlayerInput.cs.patch
  patches/tModLoader/Terraria/Item.cs.patch
  patches/tModLoader/Terraria/Main.cs.patch
  patches/tModLoader/Terraria/MessageBuffer.cs.patch
  patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
  patches/tModLoader/Terraria/ModLoader/ItemCreationContexts.cs
  patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModItem.cs
  patches/tModLoader/Terraria/ModLoader/RecipeLoader.cs
  patches/tModLoader/Terraria/Player.cs.patch
  patches/tModLoader/Terraria/Recipe.TML.cs
  patches/tModLoader/Terraria/UI/ChestUI.cs.patch
  patches/tModLoader/Terraria/UI/ItemSlot.cs.patch
  patches/tModLoader/Terraria/UI/ItemSorting.cs.patch
Labels: Feature - Hook, Benefit - Medium, Complexity - Medium

#2860 Add GlobalNPC.Send/ReceiveExtraAI
  ExampleMod/Common/GlobalNPCs/ExampleNPCNetSync.cs
  patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
  patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
Labels: Benefit - Medium, Complexity - Low, Resources - ExampleMod

#2909 Max Health and Mana Manipulation API
  ExampleMod/Common/Players/ExampleStatIncreasePlayer.cs
  ExampleMod/Common/UI/ExampleDisplaySets/ExampleReversedBarsDisplay.cs
  ExampleMod/Common/UI/ExampleDisplaySets/HP_Panel_Right.png
  ExampleMod/Common/UI/ExampleDisplaySets/MP_Panel_Right.png
  ExampleMod/Common/UI/ResourceOverlay/BarsLifeOverlay_Fill.png
  ExampleMod/Common/UI/ResourceOverlay/BarsLifeOverlay_Panel.png
  ExampleMod/Common/UI/ResourceOverlay/BarsManaOverlay_Fill.png
  ExampleMod/Common/UI/ResourceOverlay/BarsManaOverlay_Panel.png
  ExampleMod/Common/UI/ResourceOverlay/ClassicLifeOverlay.png
  ExampleMod/Common/UI/ResourceOverlay/ClassicManaOverlay.png
  ExampleMod/Common/UI/ResourceOverlay/FancyLifeOverlay_Panel.png
  ExampleMod/Common/UI/ResourceOverlay/FancyManaOverlay_Panel.png
  ExampleMod/Common/UI/ResourceOverlay/VanillaLifeOverlay.cs
  ExampleMod/Common/UI/ResourceOverlay/VanillaManaOverlay.cs
  ExampleMod/Content/Items/Consumables/ExampleLifeFruit.cs
  ExampleMod/Content/Items/Consumables/ExampleManaCrystal.cs
  ExampleMod/Content/Items/Consumables/ExampleManaCrystal.png
  ExampleMod/ExampleMod.Networking.cs
  ExampleMod/Localization/en-US.hjson
  patches/tModLoader/Terraria/Chest.cs.patch
  patches/tModLoader/Terraria/GameContent/Achievements/AchievementsHelper.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/ClassicPlayerResourcesDisplaySet.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/FancyClassicPlayerResourcesDisplaySet.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/HorizontalBarsPlayerReosurcesDisplaySet.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/IPlayerResourcesDisplaySet.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/PlayerResourceSetsManager.TML.cs
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/PlayerResourceSetsManager.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/PlayerStatsSnapshot.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/ResourceSets/ResourceDrawSettings.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/States/UICharacterCreation.cs.patch
  patches/tModLoader/Terraria/IngameOptions.cs.patch
  patches/tModLoader/Terraria/Main.cs.patch
  patches/tModLoader/Terraria/MessageBuffer.cs.patch
  patches/tModLoader/Terraria/ModLoader/Default/ConsumedStatIncreasesPlayer.cs
  patches/tModLoader/Terraria/ModLoader/Default/ModAccessorySlotPlayer.cs
  patches/tModLoader/Terraria/ModLoader/Default/ModLoaderMod.cs
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/ModLoader/ModPlayer.cs
  patches/tModLoader/Terraria/ModLoader/ModResourceDisplaySet.cs
  patches/tModLoader/Terraria/ModLoader/ModResourceOverlay.cs
  patches/tModLoader/Terraria/ModLoader/PlayerLoader.cs
  patches/tModLoader/Terraria/ModLoader/ResourceDisplaySetLoader.cs
  patches/tModLoader/Terraria/ModLoader/ResourceOverlayDrawContext.cs
  patches/tModLoader/Terraria/ModLoader/ResourceOverlayLoader.cs
  patches/tModLoader/Terraria/NPC.cs.patch
  patches/tModLoader/Terraria/Player.TML.cs
  patches/tModLoader/Terraria/Player.cs.patch
Labels: Feature - Hook, Requestor-Modders, Benefit - Medium, Complexity - High

#2707 Allow keybind text to use translated text
  ExampleMod/Common/Systems/KeybindSystem.cs
  ExampleMod/Localization/en-US.hjson
  ExampleMod/Localization/zh-Hans.hjson
  patches/tModLoader/Terraria/GameContent/UI/Elements/UIKeybindingListItem.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/States/UIManageControls.cs.patch
  patches/tModLoader/Terraria/GameInput/KeyConfiguration.cs.patch
  patches/tModLoader/Terraria/GameInput/PlayerInputProfile.TML.cs
  patches/tModLoader/Terraria/GameInput/TriggersSet.cs.patch
  patches/tModLoader/Terraria/ModLoader/KeybindLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/ModLoader/ModKeybind.cs
Labels: Feature - User Experience, Benefit - High, Complexity - Medium

#2940 [1.4] Fix mod menu always resetting on mod reload
  patches/tModLoader/Terraria/ModLoader/MenuLoader.cs
Labels: Feature - User Experience, Benefit - Low, Complexity - Low

#2983 UI Fixes
  patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
  patches/tModLoader/Terraria/ModLoader/UI/UICommon.cs
  patches/tModLoader/Terraria/ModLoader/UI/UIModInfo.cs
Labels: Feature - User Experience, Benefit - Low, Complexity - Low

#2740 Add hook ModifyCollisionData to NPC
  ExampleMod/Content/NPCs/ExampleCustomAISlimeNPC.cs
  patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
  patches/tModLoader/Terraria/ModLoader/ModNPC.cs
  patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
  patches/tModLoader/Terraria/NPC.cs.patch
Labels: Feature - Hook, Benefit - Medium, Complexity - Low, Resources - ExampleMod
