Repository tModLoader/tModLoader, pull requests merged in 2023-08, with the labels that each got.

#3453 Rework NPCID.Sets.DebuffImmunitySets
  ExampleMod/Common/GlobalNPCs/BuffImmuneGlobalNPC.cs
  ExampleMod/Common/GlobalNPCs/DamageOverTimeGlobalNPC.cs
  ExampleMod/Content/Buffs/ExampleDefenseDebuff.cs
  ExampleMod/Content/Buffs/ExampleJavelinDebuff.cs
  ExampleMod/Content/Buffs/ExampleWhipDebuff.cs
  ExampleMod/Content/NPCs/ExampleCustomAISlimeNPC.cs
  ExampleMod/Content/NPCs/MinionBoss/MinionBossBody.cs
  ExampleMod/Content/NPCs/MinionBoss/MinionBossMinion.cs
  patches/tModLoader/Terraria/DataStructures/NPCDebuffImmunityData.cs.patch
  patches/tModLoader/Terraria/ID/BuffID.TML.cs
  patches/tModLoader/Terraria/ID/BuffID.cs.patch
  patches/tModLoader/Terraria/ID/NPCID.TML.cs
  patches/tModLoader/Terraria/ID/NPCID.cs.patch
  patches/tModLoader/Terraria/NPC.TML.cs
  patches/tModLoader/Terraria/NPC.cs.patch
  tModPorter/tModPorter.Tests/TestData/ModBuffTest.Expected.cs
  tModPorter/tModPorter.Tests/TestData/ModBuffTest.cs
  tModPorter/tModPorter.Tests/TestData/ModNPCTest.Expected.cs
  tModPorter/tModPorter.Tests/TestData/ModNPCTest.cs
  tModPorter/tModPorter/Config.ModLoader.cs
  tModPorter/tModPorter/Rewriters/RenameRewriter.cs
  tModPorter/tModPorter/Rewriters/SimpleSyntaxFactory.cs
Labels: Safe to Test

#2918 Modded Emote Bubble
  ExampleMod/Common/GlobalNPCs/EmotePickerGlobalNPC.cs
  ExampleMod/Content/EmoteBubbles/ExampleBiomeEmote.cs
  ExampleMod/Content/EmoteBubbles/ExampleBiomeEmote.png
  ExampleMod/Content/EmoteBubbles/ExampleItemEmote.cs
  ExampleMod/Content/EmoteBubbles/ExampleItemEmote.png
  ExampleMod/Content/EmoteBubbles/ExamplePickaxeEmote.cs
  ExampleMod/Content/EmoteBubbles/ExamplePickaxeEmote.png
  ExampleMod/Content/EmoteBubbles/MinionBossEmote.cs
  ExampleMod/Content/EmoteBubbles/MinionBossEmote.png
  ExampleMod/Content/EmoteBubbles/NPCEmotes.cs
  ExampleMod/Content/EmoteBubbles/NPCEmotes.png
  ExampleMod/Content/Items/Tools/ExamplePickaxe.cs
  ExampleMod/Content/NPCs/ExampleBoneMerchant.cs
  ExampleMod/Content/NPCs/ExamplePerson.cs
  ExampleMod/Content/NPCs/ExampleTravelingMerchant.cs
  ExampleMod/Content/NPCs/ExampleZombieThief.cs
  ExampleMod/Localization/TranslationsNeeded.txt
  ExampleMod/Localization/en-US.hjson
  ExampleMod/Localization/ru-RU.hjson
  ExampleMod/Localization/zh-Hans.hjson
  patches/tModLoader/Terraria/Chat/Commands/EmojiCommand.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/Elements/EmoteButton.TML.cs
  patches/tModLoader/Terraria/GameContent/UI/Elements/EmoteButton.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/EmoteBubble.TML.cs
  patches/tModLoader/Terraria/GameContent/UI/EmoteBubble.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/EmoteID.TML.cs
  patches/tModLoader/Terraria/GameContent/UI/EmoteID.cs.patch
  patches/tModLoader/Terraria/GameContent/UI/States/UIEmotesMenu.cs.patch
  patches/tModLoader/Terraria/Initializers/ChatInitializer.cs.patch
  patches/tModLoader/Terraria/Lang.cs.patch
  patches/tModLoader/Terraria/Localization/LanguageManager.cs.patch
  patches/tModLoader/Terraria/MessageBuffer.cs.patch
  patches/tModLoader/Terraria/ModLoader/EmoteBubbleLoader.cs
  patches/tModLoader/Terraria/ModLoader/GlobalEmoteBubble.cs
  patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
  patches/tModLoader/Terraria/ModLoader/ModContent.cs
  patches/tModLoader/Terraria/ModLoader/ModEmoteBubble.cs
  patches/tModLoader/Terraria/ModLoader/ModNPC.cs
  patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
Labels: Feature - Hook, Benefit - Medium, Complexity - Medium

#3362 Config Elements state if they required a reload
  patches/tModLoader/Terraria/Localization/Content/de-DE/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/en-US/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/es-ES/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/fr-FR/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/it-IT/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/pl-PL/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/pt-BR/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/ru-RU/tModLoader.json
  patches/tModLoader/Terraria/Localization/Content/zh-Hans/tModLoader.json
  patches/tModLoader/Terraria/ModLoader/Config/UI/ConfigElement.cs
  solutions/TranslationsNeeded.txt
Labels: Feature - User Experience, Benefit - Medium, Complexity - Low
