Repository tModLoader/tModLoader, pull requests merged in 2023-04, with the labels that each got.

#3423 Mod/GlobalNPC.CanBeHitByNPC hooks
  patches/tModLoader/Terraria/ModLoader/GlobalNPC.cs
  patches/tModLoader/Terraria/ModLoader/ModNPC.cs
  patches/tModLoader/Terraria/ModLoader/NPCLoader.cs
Labels: Feature - Hook, Benefit - Medium, Complexity - Low

#3392 BuyItem and PreReforge split into more granular methods, Fixed savings in void bag not being considered when reforging
  patches/tModLoader/Terraria/GameContent/UI/CustomCurrencyManager.cs.patch
  patches/tModLoader/Terraria/Main.cs.patch
  patches/tModLoader/Terraria/ModLoader/GlobalItem.cs
  patches/tModLoader/Terraria/ModLoader/ItemLoader.cs
  patches/tModLoader/Terraria/ModLoader/ModItem.cs
  patches/tModLoader/Terraria/Player.TML.cs
  patches/tModLoader/Terraria/Player.cs.patch
  tModPorter/tModPorter.Tests/TestData/GlobalItemTest.Expected.cs
  tModPorter/tModPorter.Tests/TestData/ModItemTest.Expected.cs
  tModPorter/tModPorter.Tests/TestData/SimpleRenamedVanillaMembersTest.Expected.cs
  tModPorter/tModPorter.Tests/TestData/SimpleRenamedVanillaMembersTest.cs
  tModPorter/tModPorter/Config.ModLoader.cs
  tModPorter/tModPorter/Config.Terraria.cs
Labels: Bug, Benefit - Medium, Complexity - Low

#3375 Fix IME compability issue
  patches/TerrariaNetCore/ReLogic/Localization/IME/WinImm32/CandidateList.cs
  patches/TerrariaNetCore/ReLogic/Localization/IME/WinImm32/Imm.cs
  patches/TerrariaNetCore/ReLogic/Localization/IME/WinImm32/NativeMethods.cs
  patches/TerrariaNetCore/ReLogic/Localization/IME/WinImm32Ime.cs
  patches/TerrariaNetCore/ReLogic/OS/Windows/IMessageFilter.cs
  patches/TerrariaNetCore/ReLogic/OS/Windows/Message.cs
  patches/TerrariaNetCore/ReLogic/OS/Windows/Msg.cs
  patches/TerrariaNetCore/ReLogic/OS/Windows/NativeMethods.cs.patch
  patches/TerrariaNetCore/ReLogic/OS/Windows/WindowsMessageHook.cs.patch
  patches/TerrariaNetCore/ReLogic/OS/Windows/WindowsPlatform.cs.patch
  patches/TerrariaNetCore/removed_files.list
Labels: Feature - User Experience, Benefit - Medium, Complexity - High
